### ISSUE TITLE
Enhancement requests:

### ISSUE THREAD

**Issue by cah-roger-bauer** [F5Networks/terraform-gcp-bigip-module#14]
As we all are striving for simpler, standardized, faster solutions, these examples should bring more to the table.  I would expect:
* that if i used the scripts - i could quickly end up with a working config.  so much as to be added its a large learning curve,  you can spin up market place quick and easy.
* Either PROMPT for variables - or call out the following in a tfvars file...
** Quantity of hosts/instances.   Due to CFE, it should quick and easily build 1 OR 2 units, if someone wants to think about the logic behind mass scaleing and function that is much more intensive.
** availably zones, building 2 units in the same AZ doesnt make sense.
** Quantity of nics, with necessary logic to call out subcompoents.

I am sure there are others, as i dont have a completed functional product as of yet.

I would also like to see a more standard / functional use to "examples"
* how to use the examples:      use this "output.tf" instead of the one in the main branch  OR   "add this to the output.tf" in addition to what is already in there.   if something needs removed ( put this in - and take that out - it should be called out.)
* unless the file is a complete replacement, it is not helpful to add a smaller subset or different usage without documentation of why:  in example  "prefix" is listed with a default setting in examples/variables.tf.   In the main branch it exists but has no default and hence it prompts unless called out in a tfvars file or YAML file.  Service account and Image are exactly the same in both files, however if you attemper to utilize the whole file - it is missing a TON of variables?
* ** brings up another issue, why is there no example of either and or documentation to support basic function.   technical support asks for YAML files if you open a case, and i was not even using them.    An example or few examples for for.each would have saved a lot of time and frustration.   Even how to call a yaml file from a TF file, this really simplified hostnames and availability zones.

As a non-programer, i am still trying to wrap my head around the deltas:
Why in the main branch to we execute the build via "resource gcloud_computer_instance...." and it appears in the examples, the recommendation is to use module  to do the same function, but is missing a BUNCH of config to make it work.

**Comment by cah-roger-bauer** [comment]
I am unsure of what is not clear.   can you please explain which portion does make sense?

if you clone the repository - and attempt a build - it doesnt work
furthermore - the use of examples is not easily understood, you can take a example file and use it, and the portion of the example in there is not the complete stanza so some of the original config will be needed - there is no documentation about use.

**Comment by trinaths** [comment]
Created INFRAANO-642 for internal tracking.

**Comment by KrithikaChidambaram** [comment]
This was included in v1.1.6, closing this now, thanks!
