### ISSUE TITLE
Use of external IP address

### ISSUE THREAD

**Issue by cah-roger-bauer** [F5Networks/terraform-gcp-bigip-module#15]
this need to be fully explained.
* why is public IP being installed on management address this is just looking for trouble,.   if it needs to have something in the image, it should be in the image to start -and worry about upgrading once the build is near complete and hardened (secured)
* What are the recommendations an or options:
* * we abandoned forwarding rules per IP infavor of a target pool  this dramatically reduced the need for load balancing forwarding rules, which we bounce out of quota several times.   is this the use case for allowing for multiple IPs to be in the external ?  if so this could get fairly ugly with hundreds of lines in that config and or the maintenance of the objects.
* is there anyone using the byoIP feature, how is this functioning?

What is the best option to failover say 150 external IPs? on a single f5.

**Comment by trinaths** [comment]
Created INFRAANO-640 for internal tracking.

**Comment by trinaths** [comment]
@cah-roger-bauer - Please share more detailed info on how we can improve the documentation. Also, please share your requirement for this and how we can improve the same.

**Comment by KrithikaChidambaram** [comment]
This was included in v1.1.2, closing this now, thanks!
