### ISSUE TITLE
Add ability to use custom AS3/DO/TS URLs

### ISSUE THREAD

**Issue by megamattzilla** [F5Networks/terraform-gcp-bigip-module#16]
In the root directory variables.tf file there is a place to define AS3/DO/TS URLs. When a custom URL is defined to download the AnO rpms from a different location terraform fails to apply:
```
Error: Invalid index

  on ../../main.tf line 122, in data "template_file" "startup_script":
 122:     DO_VER                            = split("/", var.DO_URL)[7]
    |----------------
    | var.DO_URL is "https://example.local/rpm/f5-declarative-onboarding-1.26.0-0.noarch.rpm"

The given key does not identify an element in this collection value.
```

For airgapped or VEs without public internet access its common to download the RPMs from a locally available URL. 

I found if I hardcode the DO_VER variable in main.tf to `"v1.26.0"` I can proceed past the error.

**Comment by trinaths** [comment]
Created INFRAANO-671 for internal tracking
