### ISSUE TITLE
VM name always contains suffix id

### ISSUE THREAD

**Issue by JeffGiroux** [F5Networks/terraform-gcp-bigip-module#20]
User wants to override VM name and supply their own name. Currently you cannot supply a predetermined name because prefix is added with random suffix ID.

## Background
In reference to a past ticket https://github.com/F5Networks/terraform-gcp-bigip-module/issues/3, this VM name is not necessarily "fixed" as mentioned in previous ticket. The "f5vm01" portion has been removed, however there is now a random suffix ID appended.

current code...
```
instance_prefix = format("%s-%s", var.prefix, random_id.module_id.hex)
```

Please allow user to supply full name...and name present...then override prefix+suffix. See suggestions from previous ticket.

**Comment by trinaths** [comment]
Created [INFRAANO-728] for internal tracking.
