### ISSUE TITLE
BIG-IP VM does not initialise due to DNS failure

### ISSUE THREAD

**Issue by memes** [F5Networks/terraform-gcp-bigip-module#34]
Alerted to this issue after multiple customers complained that they could not login to BIG-IP VMs deployed with this module. My testing showed that BIG-IP VM consistently failed to resolve `cdn.f5.com` while trying to download runtime-init installer. This failure has a knock on effect, since DO - which sets the admin and bigipuser passwords, for example - is never installed.

A fix is to explicitly set DNS resolution to use GCE metadata resolver; this allows the post-nic swap script to download runtime-init, which in turn installs DO, AS3, TS, and FAST extensions and configurations.

This is also likely to be the root cause of #30 which was reported previously.

**Comment by memes** [comment]
@Azorazhai - I will reply on our email thread too, but can you verify if the fix in my PR resolves your issue?

E.g. change your Terraform to refer to my branch like below

```hcl
module "bigip" {
  source = "git::https://github.com/memes/terraform-gcp-bigip-module?ref=fix/34_resolve_dns"
  # source  = "F5Networks/bigip-module/gcp"
  # version  = "1.1.10"
  ...
}
```

**Comment by Azorazhai** [comment]
Confirmed that this fixed my issue. Thank you!

**Comment by pgouband** [comment]
Hi,

The merged will be done in the next release.
