### ISSUE TITLE
Project field is missing in main.tf

### ISSUE THREAD

**Issue by danielyaba** [F5Networks/terraform-gcp-bigip-module#39]
Hi F5,

In file "main.tf" there should be a field "_project_" under google_compute_instance.f5vm0
After adding this field to main.tf inside the modules directory it worked.

Regards,
Daniel Y.

**Comment by RavinderReddyF5** [comment]
HI @danielyaba, project field is optional parameter, if we not provide it will pick of project field of provider: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance#project

**Comment by RavinderReddyF5** [comment]
closing this issue. please open new if any problem seen
