### ISSUE TITLE
Onboarding sleep duration should be modifiable

### ISSUE THREAD

**Issue by memes** [F5Networks/terraform-gcp-bigip-module#9]
The local-exec provisioner is hard-coded to use 250 seconds of sleep so that BIG-IP can, theoretically, be onboarded and ready for next steps. This request would allow module consumers to override the value where the module is a dependency for other resources.

**Comment by memes** [comment]
PR #11 offers a potential soluton.

**Comment by cah-roger-bauer** [comment]
This block does not function on GCP, it would help if there was an solution for all platforms - or explanation of what to use for each environment

**Comment by trinaths** [comment]
Created INFRAANO-607 for internal tracking.

**Comment by RavinderReddyF5** [comment]
@memes @cah-roger-bauer hope fully added these two changes with using native https://registry.terraform.io/providers/hashicorp/time/latest/docs/resources/sleep
fixes wil be available for next release

**Comment by RavinderReddyF5** [comment]
@memes fixed in v1.1.0
